--------------------------------------------------------
--  File created - Friday-July-22-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATTENDANCERECORD
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."ATTENDANCERECORD" 
   (	"STA_ID" VARCHAR2(20 BYTE), 
	"AR_DATE" DATE, 
	"IS_LATE" CHAR(1 BYTE), 
	"IS_LEV_EARLY" CHAR(1 BYTE), 
	"IS_ABSENT" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."BOOK" 
   (	"B_ISBN" VARCHAR2(50 BYTE), 
	"B_TITLE" VARCHAR2(20 BYTE), 
	"B_AUTHOR" VARCHAR2(20 BYTE), 
	"B_LANGUAGE" VARCHAR2(20 BYTE), 
	"B_AMOUNT" NUMBER, 
	"B_PUBLISHER" VARCHAR2(20 BYTE), 
	"B_COST_PRICE" FLOAT(6), 
	"B_SELL_PRICE" FLOAT(6), 
	"SHEL_ID" VARCHAR2(20 BYTE), 
	"TP_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INCLUDE
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."INCLUDE" 
   (	"B_ISBN" VARCHAR2(13 BYTE), 
	"INCL_AMOUNT" NUMBER, 
	"REV_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LEAVERECORD
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."LEAVERECORD" 
   (	"LR_START_TIME" DATE, 
	"STA_ID" VARCHAR2(20 BYTE), 
	"LR_END_TIME" DATE, 
	"LR_DAYS" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MANAGERECORD
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."MANAGERECORD" 
   (	"MAG_ID" VARCHAR2(20 BYTE), 
	"MAG_TIME" DATE, 
	"MAG_REMARK" CHAR(1 BYTE), 
	"STA_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."MEMBER" 
   (	"MEM_ID" VARCHAR2(20 BYTE), 
	"MEM_NAME" VARCHAR2(20 BYTE), 
	"MEM_TELE" VARCHAR2(11 CHAR), 
	"MEM_GENDER" VARCHAR2(20 BYTE), 
	"MEM_BIRTH" DATE, 
	"MEM_ADDRESS" VARCHAR2(20 BYTE), 
	"MEM_OPEN_TIME" DATE, 
	"MEM_EXPIRE_TIME" DATE, 
	"LEV_TITLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBERLEVEL
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."MEMBERLEVEL" 
   (	"LEV_TITLE" VARCHAR2(20 BYTE), 
	"LEV_DISCOUNT" NUMBER(3,2), 
	"LEV_FARE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MONTHSTATISTICS
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."MONTHSTATISTICS" 
   (	"STA_ID" VARCHAR2(20 BYTE), 
	"MS_YEAR" NUMBER, 
	"MS_MONTH" NUMBER, 
	"MS_ATTEND" NUMBER, 
	"MS_ABSENT" NUMBER, 
	"MS_LEA_EARLY" NUMBER, 
	"MS_LATE" NUMBER, 
	"MS_LEAVE" NUMBER, 
	"MS_SALARY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAY
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."PAY" 
   (	"TRA_ID" VARCHAR2(20 BYTE), 
	"MEM_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMETHOD
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."PAYMETHOD" 
   (	"PM_METHOD" VARCHAR2(20 BYTE), 
	"PM_DISCOUNT" NUMBER(3,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSITION
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."POSITION" 
   (	"PO_TITLE" VARCHAR2(20 BYTE), 
	"PO_SALARY" NUMBER(5,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGION
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."REGION" 
   (	"REG_ID" VARCHAR2(20 BYTE), 
	"REG_FLOOR" NUMBER, 
	"REG_SECTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVERECORD
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."RESERVERECORD" 
   (	"REV_ID" VARCHAR2(20 BYTE), 
	"REV_TIME" DATE, 
	"IS_SUCCESS" CHAR(1 BYTE), 
	"MEM_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SELL
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."SELL" 
   (	"B_ISBN" VARCHAR2(20 BYTE), 
	"TRA_ID" VARCHAR2(20 BYTE), 
	"SEL_AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SHELF
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."SHELF" 
   (	"SHEL_ID" VARCHAR2(20 BYTE), 
	"REG_ID" VARCHAR2(20 BYTE), 
	"SHEL_CAPACITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."STAFF" 
   (	"STA_ID" VARCHAR2(20 CHAR), 
	"STA_NAME" VARCHAR2(20 CHAR), 
	"STA_GENDER" VARCHAR2(20 CHAR), 
	"STA_ADDRESS" VARCHAR2(20 CHAR), 
	"STA_BIRTH" DATE, 
	"STA_TELE" VARCHAR2(11 CHAR), 
	"STA_SIGN_DATE" DATE, 
	"PO_TITLE" VARCHAR2(20 CHAR), 
	"STA_PASSWORD" VARCHAR2(20 CHAR), 
	"STA_ON_JOB" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRADERECORD
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."TRADERECORD" 
   (	"TRA_ID" VARCHAR2(20 BYTE), 
	"TRA_TIME" DATE, 
	"TRA_MONEY" FLOAT(20), 
	"STA_ID" VARCHAR2(20 BYTE), 
	"PM_METHOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYPE
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."TYPE" 
   (	"TP_ID" VARCHAR2(20 BYTE), 
	"TP_NAME" VARCHAR2(20 BYTE), 
	"REG_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UPDATED
--------------------------------------------------------

  CREATE TABLE "C#SCOTT"."UPDATED" 
   (	"MAG_ID" VARCHAR2(20 BYTE), 
	"UPD_AMOUNT" NUMBER(*,0), 
	"B_ISBN" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View BOOK_LOCATION
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C#SCOTT"."BOOK_LOCATION" ("B_ISBN", "SHEL_ID", "REG_ID", "B_AMOUNT") AS 
  SELECT 
    BOOK.B_ISBN B_ISBN, 
    SHELF.SHEL_ID SHEL_ID, 
    SHELF.REG_ID REG_ID, 
    BOOK1.B_AMOUNT B_AMOUNT 
FROM 
    BOOK, 
    SHELF, 
    BOOK BOOK1;
REM INSERTING into C#SCOTT.ATTENDANCERECORD
SET DEFINE OFF;
Insert into C#SCOTT.ATTENDANCERECORD (STA_ID,AR_DATE,IS_LATE,IS_LEV_EARLY,IS_ABSENT) values ('1001',to_date('21-JUL-16','DD-MON-RR'),'1','0','0');
Insert into C#SCOTT.ATTENDANCERECORD (STA_ID,AR_DATE,IS_LATE,IS_LEV_EARLY,IS_ABSENT) values ('1001',to_date('12-JUL-16','DD-MON-RR'),'0','1','0');
Insert into C#SCOTT.ATTENDANCERECORD (STA_ID,AR_DATE,IS_LATE,IS_LEV_EARLY,IS_ABSENT) values ('1002',to_date('04-JUL-16','DD-MON-RR'),'1','0','0');
Insert into C#SCOTT.ATTENDANCERECORD (STA_ID,AR_DATE,IS_LATE,IS_LEV_EARLY,IS_ABSENT) values ('1002',to_date('12-JUL-16','DD-MON-RR'),'0','1','0');
Insert into C#SCOTT.ATTENDANCERECORD (STA_ID,AR_DATE,IS_LATE,IS_LEV_EARLY,IS_ABSENT) values ('1002',to_date('22-JUL-16','DD-MON-RR'),'1','1','0');
Insert into C#SCOTT.ATTENDANCERECORD (STA_ID,AR_DATE,IS_LATE,IS_LEV_EARLY,IS_ABSENT) values ('1003',to_date('22-JUL-16','DD-MON-RR'),'1','1','0');
REM INSERTING into C#SCOTT.BOOK
SET DEFINE OFF;
Insert into C#SCOTT.BOOK (B_ISBN,B_TITLE,B_AUTHOR,B_LANGUAGE,B_AMOUNT,B_PUBLISHER,B_COST_PRICE,B_SELL_PRICE,SHEL_ID,TP_ID) values ('123456654321','SoftwareReuse','Sam','English',86,'SeniorEducation',30,20,'A501','1006');
Insert into C#SCOTT.BOOK (B_ISBN,B_TITLE,B_AUTHOR,B_LANGUAGE,B_AMOUNT,B_PUBLISHER,B_COST_PRICE,B_SELL_PRICE,SHEL_ID,TP_ID) values ('4638293475234','Linux操作系统','刘萧','中文',27,'人民出版社',100,80,'A501','1004');
Insert into C#SCOTT.BOOK (B_ISBN,B_TITLE,B_AUTHOR,B_LANGUAGE,B_AMOUNT,B_PUBLISHER,B_COST_PRICE,B_SELL_PRICE,SHEL_ID,TP_ID) values ('7777777777777','数据库原理','张萌','英文',77,'人民出版社',60,90,'A501','1004');
Insert into C#SCOTT.BOOK (B_ISBN,B_TITLE,B_AUTHOR,B_LANGUAGE,B_AMOUNT,B_PUBLISHER,B_COST_PRICE,B_SELL_PRICE,SHEL_ID,TP_ID) values ('1234567890123','南海军事分析','王建锋','中文',50,'新华出版社',40,50,'C401','1002');
REM INSERTING into C#SCOTT.INCLUDE
SET DEFINE OFF;
Insert into C#SCOTT.INCLUDE (B_ISBN,INCL_AMOUNT,REV_ID) values ('7777777777777',3,'4004');
Insert into C#SCOTT.INCLUDE (B_ISBN,INCL_AMOUNT,REV_ID) values ('123456654321',3,'4003');
Insert into C#SCOTT.INCLUDE (B_ISBN,INCL_AMOUNT,REV_ID) values ('123456654321',3,'4004');
Insert into C#SCOTT.INCLUDE (B_ISBN,INCL_AMOUNT,REV_ID) values ('7777777777777',10,'4005');
Insert into C#SCOTT.INCLUDE (B_ISBN,INCL_AMOUNT,REV_ID) values ('7777777777777',3,'4006');
Insert into C#SCOTT.INCLUDE (B_ISBN,INCL_AMOUNT,REV_ID) values ('123456654321',3,'4006');
Insert into C#SCOTT.INCLUDE (B_ISBN,INCL_AMOUNT,REV_ID) values ('7777777777777',10,'4001');
Insert into C#SCOTT.INCLUDE (B_ISBN,INCL_AMOUNT,REV_ID) values ('123456654321',10,'4001');
REM INSERTING into C#SCOTT.LEAVERECORD
SET DEFINE OFF;
Insert into C#SCOTT.LEAVERECORD (LR_START_TIME,STA_ID,LR_END_TIME,LR_DAYS) values (to_date('04-FEB-16','DD-MON-RR'),'1002',to_date('07-FEB-16','DD-MON-RR'),3);
Insert into C#SCOTT.LEAVERECORD (LR_START_TIME,STA_ID,LR_END_TIME,LR_DAYS) values (to_date('31-JUL-16','DD-MON-RR'),'1001',to_date('12-AUG-16','DD-MON-RR'),12);
Insert into C#SCOTT.LEAVERECORD (LR_START_TIME,STA_ID,LR_END_TIME,LR_DAYS) values (to_date('20-AUG-16','DD-MON-RR'),'1002',to_date('22-AUG-16','DD-MON-RR'),2);
Insert into C#SCOTT.LEAVERECORD (LR_START_TIME,STA_ID,LR_END_TIME,LR_DAYS) values (to_date('12-JUL-16','DD-MON-RR'),'1002',to_date('15-JUL-16','DD-MON-RR'),3);
Insert into C#SCOTT.LEAVERECORD (LR_START_TIME,STA_ID,LR_END_TIME,LR_DAYS) values (to_date('01-AUG-16','DD-MON-RR'),'1003',to_date('06-AUG-16','DD-MON-RR'),5);
REM INSERTING into C#SCOTT.MANAGERECORD
SET DEFINE OFF;
Insert into C#SCOTT.MANAGERECORD (MAG_ID,MAG_TIME,MAG_REMARK,STA_ID) values ('3',to_date('22-JUL-16','DD-MON-RR'),'1','1003');
Insert into C#SCOTT.MANAGERECORD (MAG_ID,MAG_TIME,MAG_REMARK,STA_ID) values ('1',to_date('22-JUL-16','DD-MON-RR'),'1','1003');
Insert into C#SCOTT.MANAGERECORD (MAG_ID,MAG_TIME,MAG_REMARK,STA_ID) values ('2',to_date('22-JUL-16','DD-MON-RR'),'1','1003');
Insert into C#SCOTT.MANAGERECORD (MAG_ID,MAG_TIME,MAG_REMARK,STA_ID) values ('7',to_date('22-JUL-16','DD-MON-RR'),'1','1002');
Insert into C#SCOTT.MANAGERECORD (MAG_ID,MAG_TIME,MAG_REMARK,STA_ID) values ('8',to_date('22-JUL-16','DD-MON-RR'),'0','1002');
Insert into C#SCOTT.MANAGERECORD (MAG_ID,MAG_TIME,MAG_REMARK,STA_ID) values ('6',to_date('22-JUL-16','DD-MON-RR'),'0','1003');
Insert into C#SCOTT.MANAGERECORD (MAG_ID,MAG_TIME,MAG_REMARK,STA_ID) values ('4',to_date('22-JUL-16','DD-MON-RR'),'1','1003');
Insert into C#SCOTT.MANAGERECORD (MAG_ID,MAG_TIME,MAG_REMARK,STA_ID) values ('5',to_date('22-JUL-16','DD-MON-RR'),'0','1003');
REM INSERTING into C#SCOTT.MEMBER
SET DEFINE OFF;
Insert into C#SCOTT.MEMBER (MEM_ID,MEM_NAME,MEM_TELE,MEM_GENDER,MEM_BIRTH,MEM_ADDRESS,MEM_OPEN_TIME,MEM_EXPIRE_TIME,LEV_TITLE) values ('1007','abc','12345678998','男',to_date('04-MAR-97','DD-MON-RR'),'adress',to_date('22-JUL-16','DD-MON-RR'),to_date('22-OCT-16','DD-MON-RR'),'senior');
Insert into C#SCOTT.MEMBER (MEM_ID,MEM_NAME,MEM_TELE,MEM_GENDER,MEM_BIRTH,MEM_ADDRESS,MEM_OPEN_TIME,MEM_EXPIRE_TIME,LEV_TITLE) values ('1008','2333','12345678901','男',to_date('04-MAR-97','DD-MON-RR'),'北京',to_date('22-JUL-16','DD-MON-RR'),to_date('22-OCT-16','DD-MON-RR'),'senior');
Insert into C#SCOTT.MEMBER (MEM_ID,MEM_NAME,MEM_TELE,MEM_GENDER,MEM_BIRTH,MEM_ADDRESS,MEM_OPEN_TIME,MEM_EXPIRE_TIME,LEV_TITLE) values ('1002','ZhangSan','18221178901','man',to_date('01-FEB-96','DD-MON-RR'),'Shanghai',to_date('04-MAY-16','DD-MON-RR'),to_date('04-MAY-17','DD-MON-RR'),'senior');
Insert into C#SCOTT.MEMBER (MEM_ID,MEM_NAME,MEM_TELE,MEM_GENDER,MEM_BIRTH,MEM_ADDRESS,MEM_OPEN_TIME,MEM_EXPIRE_TIME,LEV_TITLE) values ('1006','abc','12345678901','女',to_date('04-MAR-16','DD-MON-RR'),'adress',to_date('22-JUL-16','DD-MON-RR'),to_date('22-OCT-16','DD-MON-RR'),'senior');
Insert into C#SCOTT.MEMBER (MEM_ID,MEM_NAME,MEM_TELE,MEM_GENDER,MEM_BIRTH,MEM_ADDRESS,MEM_OPEN_TIME,MEM_EXPIRE_TIME,LEV_TITLE) values ('1005','Lufy','13333333333','?',to_date('08-OCT-95','DD-MON-RR'),'adfgfda',to_date('22-JUL-16','DD-MON-RR'),to_date('22-OCT-16','DD-MON-RR'),'middle');
Insert into C#SCOTT.MEMBER (MEM_ID,MEM_NAME,MEM_TELE,MEM_GENDER,MEM_BIRTH,MEM_ADDRESS,MEM_OPEN_TIME,MEM_EXPIRE_TIME,LEV_TITLE) values ('1003','ooo','13333333333','?',to_date('08-OCT-95','DD-MON-RR'),'adfgfda',to_date('22-JUL-16','DD-MON-RR'),to_date('22-OCT-16','DD-MON-RR'),'senior');
Insert into C#SCOTT.MEMBER (MEM_ID,MEM_NAME,MEM_TELE,MEM_GENDER,MEM_BIRTH,MEM_ADDRESS,MEM_OPEN_TIME,MEM_EXPIRE_TIME,LEV_TITLE) values ('1004','ooo','13333333333','?',to_date('08-OCT-95','DD-MON-RR'),'adfgfda',to_date('22-JUL-16','DD-MON-RR'),to_date('22-OCT-16','DD-MON-RR'),'senior');
REM INSERTING into C#SCOTT.MEMBERLEVEL
SET DEFINE OFF;
Insert into C#SCOTT.MEMBERLEVEL (LEV_TITLE,LEV_DISCOUNT,LEV_FARE) values ('senior',0.75,40);
Insert into C#SCOTT.MEMBERLEVEL (LEV_TITLE,LEV_DISCOUNT,LEV_FARE) values ('middle',0.85,30);
Insert into C#SCOTT.MEMBERLEVEL (LEV_TITLE,LEV_DISCOUNT,LEV_FARE) values ('junior',0.9,20);
REM INSERTING into C#SCOTT.MONTHSTATISTICS
SET DEFINE OFF;
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1004',2016,7,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1004',2016,8,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1004',2016,9,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1004',2016,10,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1004',2016,11,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1004',2016,12,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1004',2017,1,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1004',2017,2,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1004',2017,3,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1004',2017,4,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1004',2017,5,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1004',2017,6,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1002',2016,8,0,0,0,0,2,3840);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1002',2016,9,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1002',2016,10,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1002',2016,11,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1002',2016,12,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1002',2017,1,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1002',2017,2,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1002',2017,3,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1002',2017,4,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1002',2017,5,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1002',2017,6,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1003',2016,7,1,0,1,1,0,4460);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1001',2016,7,2,0,1,1,12,6000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1001',2016,8,0,0,0,0,0,7000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1001',2016,9,0,0,0,0,0,7000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1001',2016,10,0,0,0,0,0,7000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1001',2016,11,0,0,0,0,0,7000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1001',2016,12,0,0,0,0,0,7000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1001',2017,1,0,0,0,0,0,7000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1001',2017,2,0,0,0,0,0,7000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1001',2017,3,0,0,0,0,0,7000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1001',2017,4,0,0,0,0,0,7000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1001',2017,5,0,0,0,0,0,7000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1001',2017,6,0,0,0,0,0,7000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1002',2016,7,3,0,2,2,3,3680);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1003',2016,8,0,0,0,0,5,4100);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1003',2016,9,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1003',2016,10,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1003',2016,11,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1003',2016,12,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1003',2017,1,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1003',2017,2,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1003',2017,3,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1003',2017,4,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1003',2017,5,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1003',2017,6,0,0,0,0,0,4500);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1005',2016,7,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1005',2016,8,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1005',2016,9,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1005',2016,10,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1005',2016,11,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1005',2016,12,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1005',2017,1,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1005',2017,2,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1005',2017,3,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1005',2017,4,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1005',2017,5,0,0,0,0,0,4000);
Insert into C#SCOTT.MONTHSTATISTICS (STA_ID,MS_YEAR,MS_MONTH,MS_ATTEND,MS_ABSENT,MS_LEA_EARLY,MS_LATE,MS_LEAVE,MS_SALARY) values ('1005',2017,6,0,0,0,0,0,4000);
REM INSERTING into C#SCOTT.PAY
SET DEFINE OFF;
Insert into C#SCOTT.PAY (TRA_ID,MEM_ID) values ('5002','1002');
Insert into C#SCOTT.PAY (TRA_ID,MEM_ID) values ('5003','1002');
Insert into C#SCOTT.PAY (TRA_ID,MEM_ID) values ('5001','1003');
REM INSERTING into C#SCOTT.PAYMETHOD
SET DEFINE OFF;
Insert into C#SCOTT.PAYMETHOD (PM_METHOD,PM_DISCOUNT) values ('money',0.99);
Insert into C#SCOTT.PAYMETHOD (PM_METHOD,PM_DISCOUNT) values ('微信',0.95);
Insert into C#SCOTT.PAYMETHOD (PM_METHOD,PM_DISCOUNT) values ('支付宝',0.95);
Insert into C#SCOTT.PAYMETHOD (PM_METHOD,PM_DISCOUNT) values ('网银',0.97);
REM INSERTING into C#SCOTT.POSITION
SET DEFINE OFF;
Insert into C#SCOTT.POSITION (PO_TITLE,PO_SALARY) values ('Manager',7000);
Insert into C#SCOTT.POSITION (PO_TITLE,PO_SALARY) values ('Cashier',4500);
Insert into C#SCOTT.POSITION (PO_TITLE,PO_SALARY) values ('Clerk',4000);
REM INSERTING into C#SCOTT.REGION
SET DEFINE OFF;
Insert into C#SCOTT.REGION (REG_ID,REG_FLOOR,REG_SECTION) values ('501',5,'a');
Insert into C#SCOTT.REGION (REG_ID,REG_FLOOR,REG_SECTION) values ('301',3,'b');
Insert into C#SCOTT.REGION (REG_ID,REG_FLOOR,REG_SECTION) values ('401',4,'c');
REM INSERTING into C#SCOTT.RESERVERECORD
SET DEFINE OFF;
Insert into C#SCOTT.RESERVERECORD (REV_ID,REV_TIME,IS_SUCCESS,MEM_ID) values ('4004',to_date('22-JUL-16','DD-MON-RR'),'0','1002');
Insert into C#SCOTT.RESERVERECORD (REV_ID,REV_TIME,IS_SUCCESS,MEM_ID) values ('4002',to_date('22-JUL-16','DD-MON-RR'),'0','1002');
Insert into C#SCOTT.RESERVERECORD (REV_ID,REV_TIME,IS_SUCCESS,MEM_ID) values ('4003',to_date('22-JUL-16','DD-MON-RR'),'0','1002');
Insert into C#SCOTT.RESERVERECORD (REV_ID,REV_TIME,IS_SUCCESS,MEM_ID) values ('4005',to_date('22-JUL-16','DD-MON-RR'),'0','1003');
Insert into C#SCOTT.RESERVERECORD (REV_ID,REV_TIME,IS_SUCCESS,MEM_ID) values ('4006',to_date('22-JUL-16','DD-MON-RR'),'0','1003');
Insert into C#SCOTT.RESERVERECORD (REV_ID,REV_TIME,IS_SUCCESS,MEM_ID) values ('4001',to_date('22-JUL-16','DD-MON-RR'),'1','1002');
REM INSERTING into C#SCOTT.SELL
SET DEFINE OFF;
Insert into C#SCOTT.SELL (B_ISBN,TRA_ID,SEL_AMOUNT) values ('7777777777777','5001',4);
Insert into C#SCOTT.SELL (B_ISBN,TRA_ID,SEL_AMOUNT) values ('7777777777777','5003',1);
Insert into C#SCOTT.SELL (B_ISBN,TRA_ID,SEL_AMOUNT) values ('123456654321','5003',1);
Insert into C#SCOTT.SELL (B_ISBN,TRA_ID,SEL_AMOUNT) values ('123456654321','5002',10);
Insert into C#SCOTT.SELL (B_ISBN,TRA_ID,SEL_AMOUNT) values ('7777777777777','5002',10);
REM INSERTING into C#SCOTT.SHELF
SET DEFINE OFF;
Insert into C#SCOTT.SHELF (SHEL_ID,REG_ID,SHEL_CAPACITY) values ('B301','301',140);
Insert into C#SCOTT.SHELF (SHEL_ID,REG_ID,SHEL_CAPACITY) values ('A501','501',404);
Insert into C#SCOTT.SHELF (SHEL_ID,REG_ID,SHEL_CAPACITY) values ('C401','401',46);
REM INSERTING into C#SCOTT.STAFF
SET DEFINE OFF;
Insert into C#SCOTT.STAFF (STA_ID,STA_NAME,STA_GENDER,STA_ADDRESS,STA_BIRTH,STA_TELE,STA_SIGN_DATE,PO_TITLE,STA_PASSWORD,STA_ON_JOB) values ('1004','Lily','woman','Shanghai',to_date('16-MAR-90','DD-MON-RR'),'18221190235',to_date('16-MAR-90','DD-MON-RR'),'Cashier','tiger','yes');
Insert into C#SCOTT.STAFF (STA_ID,STA_NAME,STA_GENDER,STA_ADDRESS,STA_BIRTH,STA_TELE,STA_SIGN_DATE,PO_TITLE,STA_PASSWORD,STA_ON_JOB) values ('1003','Jim','man','Beijing',to_date('07-MAR-92','DD-MON-RR'),'1892342781',to_date('12-MAR-91','DD-MON-RR'),'Clerk','tiger','Yes');
Insert into C#SCOTT.STAFF (STA_ID,STA_NAME,STA_GENDER,STA_ADDRESS,STA_BIRTH,STA_TELE,STA_SIGN_DATE,PO_TITLE,STA_PASSWORD,STA_ON_JOB) values ('1001','huangrui','man','上海',to_date('08-JUN-93','DD-MON-RR'),'18221112345',to_date('06-JUN-01','DD-MON-RR'),'Manager','tiger','Yes');
Insert into C#SCOTT.STAFF (STA_ID,STA_NAME,STA_GENDER,STA_ADDRESS,STA_BIRTH,STA_TELE,STA_SIGN_DATE,PO_TITLE,STA_PASSWORD,STA_ON_JOB) values ('1002','Jane','woman','Shanghai',to_date('18-FEB-95','DD-MON-RR'),'1567293571',to_date('01-FEB-95','DD-MON-RR'),'Clerk','tiger','Yes');
Insert into C#SCOTT.STAFF (STA_ID,STA_NAME,STA_GENDER,STA_ADDRESS,STA_BIRTH,STA_TELE,STA_SIGN_DATE,PO_TITLE,STA_PASSWORD,STA_ON_JOB) values ('1005','Billy','man','Hangzhou',to_date('09-JAN-90','DD-MON-RR'),'18221190266',to_date('09-JAN-90','DD-MON-RR'),'Clerk','123','yes');
REM INSERTING into C#SCOTT.TRADERECORD
SET DEFINE OFF;
Insert into C#SCOTT.TRADERECORD (TRA_ID,TRA_TIME,TRA_MONEY,STA_ID,PM_METHOD) values ('5001',to_date('22-JUL-16','DD-MON-RR'),267.3,'1004','money');
Insert into C#SCOTT.TRADERECORD (TRA_ID,TRA_TIME,TRA_MONEY,STA_ID,PM_METHOD) values ('5002',to_date('22-JUL-16','DD-MON-RR'),783.75,'1004','支付宝');
Insert into C#SCOTT.TRADERECORD (TRA_ID,TRA_TIME,TRA_MONEY,STA_ID,PM_METHOD) values ('5003',to_date('22-JUL-16','DD-MON-RR'),78.375,'1004','微信');
REM INSERTING into C#SCOTT.TYPE
SET DEFINE OFF;
Insert into C#SCOTT.TYPE (TP_ID,TP_NAME,REG_ID) values ('1007','aaa','501');
Insert into C#SCOTT.TYPE (TP_ID,TP_NAME,REG_ID) values ('1005','math','501');
Insert into C#SCOTT.TYPE (TP_ID,TP_NAME,REG_ID) values ('1006','Computer','501');
Insert into C#SCOTT.TYPE (TP_ID,TP_NAME,REG_ID) values ('1008','1','501');
Insert into C#SCOTT.TYPE (TP_ID,TP_NAME,REG_ID) values ('1003','体育','301');
Insert into C#SCOTT.TYPE (TP_ID,TP_NAME,REG_ID) values ('1001','文学','301');
Insert into C#SCOTT.TYPE (TP_ID,TP_NAME,REG_ID) values ('1002','军事','401');
Insert into C#SCOTT.TYPE (TP_ID,TP_NAME,REG_ID) values ('1004','计算机','501');
REM INSERTING into C#SCOTT.UPDATED
SET DEFINE OFF;
Insert into C#SCOTT.UPDATED (MAG_ID,UPD_AMOUNT,B_ISBN) values ('1',10,'123456654321');
Insert into C#SCOTT.UPDATED (MAG_ID,UPD_AMOUNT,B_ISBN) values ('2',10,'7777777777777');
Insert into C#SCOTT.UPDATED (MAG_ID,UPD_AMOUNT,B_ISBN) values ('3',10,'7777777777777');
Insert into C#SCOTT.UPDATED (MAG_ID,UPD_AMOUNT,B_ISBN) values ('7',30,'4638293475234');
Insert into C#SCOTT.UPDATED (MAG_ID,UPD_AMOUNT,B_ISBN) values ('8',3,'7777777777777');
Insert into C#SCOTT.UPDATED (MAG_ID,UPD_AMOUNT,B_ISBN) values ('6',4,'7777777777777');
Insert into C#SCOTT.UPDATED (MAG_ID,UPD_AMOUNT,B_ISBN) values ('4',1,'7777777777777');
Insert into C#SCOTT.UPDATED (MAG_ID,UPD_AMOUNT,B_ISBN) values ('5',2,'7777777777777');
--------------------------------------------------------
--  DDL for Index PK_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PK_TYPE" ON "C#SCOTT"."TYPE" ("TP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_REV
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PK_REV" ON "C#SCOTT"."RESERVERECORD" ("REV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEM_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."MEM_ID" ON "C#SCOTT"."MEMBER" ("MEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_INCLUDE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PK_INCLUDE" ON "C#SCOTT"."INCLUDE" ("B_ISBN", "REV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REG_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."REG_ID" ON "C#SCOTT"."REGION" ("REG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MAG_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."MAG_ID" ON "C#SCOTT"."MANAGERECORD" ("MAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PK_MS" ON "C#SCOTT"."MONTHSTATISTICS" ("STA_ID", "MS_YEAR", "MS_MONTH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PK_STA" ON "C#SCOTT"."STAFF" ("STA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TRA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PK_TRA" ON "C#SCOTT"."TRADERECORD" ("TRA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SELL
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PK_SELL" ON "C#SCOTT"."SELL" ("B_ISBN", "TRA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PKEY3-4
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PKEY3-4" ON "C#SCOTT"."POSITION" ("PO_TITLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PK" ON "C#SCOTT"."BOOK" ("B_ISBN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index L_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."L_PK" ON "C#SCOTT"."MEMBERLEVEL" ("LEV_TITLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ATTENDANCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PK_ATTENDANCE" ON "C#SCOTT"."ATTENDANCERECORD" ("STA_ID", "AR_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SHEL_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."SHEL_ID" ON "C#SCOTT"."SHELF" ("SHEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LR_RECORD
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PK_LR_RECORD" ON "C#SCOTT"."LEAVERECORD" ("STA_ID", "LR_START_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PAYMETHOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PAYMETHOD_PK" ON "C#SCOTT"."PAYMETHOD" ("PM_METHOD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PAY
--------------------------------------------------------

  CREATE UNIQUE INDEX "C#SCOTT"."PK_PAY" ON "C#SCOTT"."PAY" ("MEM_ID", "TRA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MANAGERECORD
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."MANAGERECORD" MODIFY ("STA_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MANAGERECORD" ADD CONSTRAINT "MAG_ID" PRIMARY KEY ("MAG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C#SCOTT"."MANAGERECORD" MODIFY ("MAG_TIME" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MANAGERECORD" MODIFY ("MAG_REMARK" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MANAGERECORD" ADD CONSTRAINT "CHECK_REMARK" CHECK (MAG_REMARK in ( '0', '1')) ENABLE;
--------------------------------------------------------
--  Constraints for Table ATTENDANCERECORD
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."ATTENDANCERECORD" MODIFY ("STA_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."ATTENDANCERECORD" MODIFY ("AR_DATE" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."ATTENDANCERECORD" MODIFY ("IS_LATE" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."ATTENDANCERECORD" MODIFY ("IS_LEV_EARLY" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."ATTENDANCERECORD" MODIFY ("IS_ABSENT" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."ATTENDANCERECORD" ADD CONSTRAINT "CHECK_IS_LATE" CHECK (IS_LATE  in ( '0','1' )) ENABLE;
  ALTER TABLE "C#SCOTT"."ATTENDANCERECORD" ADD CONSTRAINT "CHECK_IS_EARLY" CHECK (IS_LEV_EARLY  in ( '0','1' )) ENABLE;
  ALTER TABLE "C#SCOTT"."ATTENDANCERECORD" ADD CONSTRAINT "CHECK_IS_ABSENT" CHECK (IS_ABSENT  in ( '0','1' )) ENABLE;
  ALTER TABLE "C#SCOTT"."ATTENDANCERECORD" ADD CONSTRAINT "PK_ATTENDANCE" PRIMARY KEY ("STA_ID", "AR_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SHELF
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."SHELF" MODIFY ("SHEL_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."SHELF" MODIFY ("REG_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."SHELF" MODIFY ("SHEL_CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."SHELF" ADD CONSTRAINT "SHEL_ID" PRIMARY KEY ("SHEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVERECORD
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."RESERVERECORD" MODIFY ("REV_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."RESERVERECORD" MODIFY ("REV_TIME" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."RESERVERECORD" MODIFY ("IS_SUCCESS" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."RESERVERECORD" ADD CONSTRAINT "CHECK_IS_SUCCESS" CHECK (IS_SUCCESS in ( '0', '1' )) ENABLE;
  ALTER TABLE "C#SCOTT"."RESERVERECORD" ADD CONSTRAINT "PK_REV" PRIMARY KEY ("REV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C#SCOTT"."RESERVERECORD" MODIFY ("MEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."STAFF" MODIFY ("STA_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."STAFF" MODIFY ("STA_TELE" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."STAFF" MODIFY ("STA_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."STAFF" MODIFY ("STA_GENDER" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."STAFF" ADD CONSTRAINT "PK_STA" PRIMARY KEY ("STA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C#SCOTT"."STAFF" MODIFY ("STA_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGION
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."REGION" MODIFY ("REG_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."REGION" MODIFY ("REG_FLOOR" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."REGION" MODIFY ("REG_SECTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."MEMBER" MODIFY ("MEM_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MEMBER" MODIFY ("MEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MEMBER" MODIFY ("MEM_TELE" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MEMBER" MODIFY ("MEM_GENDER" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MEMBER" MODIFY ("MEM_OPEN_TIME" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MEMBER" MODIFY ("MEM_EXPIRE_TIME" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MEMBER" MODIFY ("LEV_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UPDATED
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."UPDATED" MODIFY ("MAG_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."UPDATED" MODIFY ("UPD_AMOUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MONTHSTATISTICS
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."MONTHSTATISTICS" MODIFY ("STA_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MONTHSTATISTICS" MODIFY ("MS_YEAR" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MONTHSTATISTICS" MODIFY ("MS_MONTH" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MONTHSTATISTICS" MODIFY ("MS_ATTEND" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MONTHSTATISTICS" MODIFY ("MS_ABSENT" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MONTHSTATISTICS" MODIFY ("MS_LEA_EARLY" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MONTHSTATISTICS" MODIFY ("MS_LATE" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MONTHSTATISTICS" MODIFY ("MS_LEAVE" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MONTHSTATISTICS" MODIFY ("MS_SALARY" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MONTHSTATISTICS" ADD CONSTRAINT "PK_MS" PRIMARY KEY ("STA_ID", "MS_YEAR", "MS_MONTH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMETHOD
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."PAYMETHOD" MODIFY ("PM_METHOD" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."PAYMETHOD" MODIFY ("PM_DISCOUNT" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."PAYMETHOD" ADD CONSTRAINT "PAYMETHOD_PK" PRIMARY KEY ("PM_METHOD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSITION
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."POSITION" MODIFY ("PO_SALARY" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."POSITION" ADD CONSTRAINT "PKEY3-4" PRIMARY KEY ("PO_TITLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LEAVERECORD
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."LEAVERECORD" MODIFY ("LR_START_TIME" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."LEAVERECORD" MODIFY ("STA_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."LEAVERECORD" MODIFY ("LR_END_TIME" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."LEAVERECORD" MODIFY ("LR_DAYS" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."LEAVERECORD" ADD CONSTRAINT "PK_LR_RECORD" PRIMARY KEY ("STA_ID", "LR_START_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SELL
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."SELL" MODIFY ("B_ISBN" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."SELL" MODIFY ("TRA_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."SELL" MODIFY ("SEL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."SELL" ADD CONSTRAINT "PK_SELL" PRIMARY KEY ("B_ISBN", "TRA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAY
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."PAY" MODIFY ("TRA_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."PAY" MODIFY ("MEM_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."PAY" ADD CONSTRAINT "PK_PAY" PRIMARY KEY ("MEM_ID", "TRA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."BOOK" MODIFY ("B_ISBN" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."BOOK" MODIFY ("B_TITLE" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."BOOK" MODIFY ("B_AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."BOOK" MODIFY ("B_LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."BOOK" MODIFY ("B_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."BOOK" MODIFY ("B_PUBLISHER" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."BOOK" MODIFY ("B_COST_PRICE" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."BOOK" MODIFY ("B_SELL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."BOOK" MODIFY ("SHEL_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."BOOK" MODIFY ("TP_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."BOOK" ADD CONSTRAINT "PK" PRIMARY KEY ("B_ISBN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBERLEVEL
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."MEMBERLEVEL" MODIFY ("LEV_TITLE" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MEMBERLEVEL" MODIFY ("LEV_DISCOUNT" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MEMBERLEVEL" MODIFY ("LEV_FARE" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."MEMBERLEVEL" ADD CONSTRAINT "L_PK" PRIMARY KEY ("LEV_TITLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INCLUDE
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."INCLUDE" MODIFY ("REV_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."INCLUDE" MODIFY ("B_ISBN" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."INCLUDE" MODIFY ("INCL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."INCLUDE" ADD CONSTRAINT "PK_INCLUDE" PRIMARY KEY ("B_ISBN", "REV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRADERECORD
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."TRADERECORD" MODIFY ("TRA_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."TRADERECORD" MODIFY ("TRA_TIME" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."TRADERECORD" MODIFY ("TRA_MONEY" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."TRADERECORD" ADD CONSTRAINT "PK_TRA" PRIMARY KEY ("TRA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C#SCOTT"."TRADERECORD" MODIFY ("STA_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."TRADERECORD" MODIFY ("PM_METHOD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPE
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."TYPE" MODIFY ("TP_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."TYPE" MODIFY ("TP_NAME" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."TYPE" MODIFY ("REG_ID" NOT NULL ENABLE);
  ALTER TABLE "C#SCOTT"."TYPE" ADD CONSTRAINT "PK_TYPE" PRIMARY KEY ("TP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTENDANCERECORD
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."ATTENDANCERECORD" ADD CONSTRAINT "CONSTRAINT1" FOREIGN KEY ("STA_ID")
	  REFERENCES "C#SCOTT"."STAFF" ("STA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."BOOK" ADD CONSTRAINT "FK1_BOOK" FOREIGN KEY ("SHEL_ID")
	  REFERENCES "C#SCOTT"."SHELF" ("SHEL_ID") ENABLE;
  ALTER TABLE "C#SCOTT"."BOOK" ADD CONSTRAINT "FK2_BOOK" FOREIGN KEY ("TP_ID")
	  REFERENCES "C#SCOTT"."TYPE" ("TP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INCLUDE
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."INCLUDE" ADD CONSTRAINT "FK1_INCLUDE" FOREIGN KEY ("REV_ID")
	  REFERENCES "C#SCOTT"."RESERVERECORD" ("REV_ID") ENABLE;
  ALTER TABLE "C#SCOTT"."INCLUDE" ADD CONSTRAINT "FK2_INCLUDE" FOREIGN KEY ("B_ISBN")
	  REFERENCES "C#SCOTT"."BOOK" ("B_ISBN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LEAVERECORD
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."LEAVERECORD" ADD CONSTRAINT "FK_LR_RECORD" FOREIGN KEY ("STA_ID")
	  REFERENCES "C#SCOTT"."STAFF" ("STA_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANAGERECORD
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."MANAGERECORD" ADD CONSTRAINT "FK_MANAGERECORD" FOREIGN KEY ("STA_ID")
	  REFERENCES "C#SCOTT"."STAFF" ("STA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."MEMBER" ADD CONSTRAINT "FK_MEMBER" FOREIGN KEY ("LEV_TITLE")
	  REFERENCES "C#SCOTT"."MEMBERLEVEL" ("LEV_TITLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MONTHSTATISTICS
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."MONTHSTATISTICS" ADD CONSTRAINT "FK_MS" FOREIGN KEY ("STA_ID")
	  REFERENCES "C#SCOTT"."STAFF" ("STA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAY
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."PAY" ADD CONSTRAINT "FK1_PAY" FOREIGN KEY ("TRA_ID")
	  REFERENCES "C#SCOTT"."TRADERECORD" ("TRA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SELL
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."SELL" ADD CONSTRAINT "FK1_SELL" FOREIGN KEY ("B_ISBN")
	  REFERENCES "C#SCOTT"."BOOK" ("B_ISBN") ENABLE;
  ALTER TABLE "C#SCOTT"."SELL" ADD CONSTRAINT "FK2_SELL" FOREIGN KEY ("TRA_ID")
	  REFERENCES "C#SCOTT"."TRADERECORD" ("TRA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."STAFF" ADD CONSTRAINT "FK_STA" FOREIGN KEY ("PO_TITLE")
	  REFERENCES "C#SCOTT"."POSITION" ("PO_TITLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRADERECORD
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."TRADERECORD" ADD CONSTRAINT "FK1_TRA" FOREIGN KEY ("STA_ID")
	  REFERENCES "C#SCOTT"."STAFF" ("STA_ID") ENABLE;
  ALTER TABLE "C#SCOTT"."TRADERECORD" ADD CONSTRAINT "FK2_TRA" FOREIGN KEY ("PM_METHOD")
	  REFERENCES "C#SCOTT"."PAYMETHOD" ("PM_METHOD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UPDATED
--------------------------------------------------------

  ALTER TABLE "C#SCOTT"."UPDATED" ADD CONSTRAINT "FK1_UPDATED" FOREIGN KEY ("MAG_ID")
	  REFERENCES "C#SCOTT"."MANAGERECORD" ("MAG_ID") ENABLE;
  ALTER TABLE "C#SCOTT"."UPDATED" ADD CONSTRAINT "FK2_UPDATED" FOREIGN KEY ("B_ISBN")
	  REFERENCES "C#SCOTT"."BOOK" ("B_ISBN") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ATTENDANCERECORD_TRIGGER1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C#SCOTT"."ATTENDANCERECORD_TRIGGER1" 
  AFTER
  INSERT
  ON "ATTENDANCERECORD"
  REFERENCING NEW AS NROW
  FOR EACH ROW
DECLARE
BEGIN
  UPDATE MONTHSTATISTICS SET MONTHSTATISTICS.MS_ATTEND=MONTHSTATISTICS.MS_ATTEND+1
  WHERE MONTHSTATISTICS.STA_ID=:NROW.STA_ID AND MONTHSTATISTICS.MS_YEAR=EXTRACT(year from :NROW.AR_DATE) AND
        MONTHSTATISTICS.MS_MONTH=EXTRACT(month from :NROW.AR_DATE);
  IF :NROW.IS_LATE='1'
  THEN
     UPDATE MONTHSTATISTICS SET MONTHSTATISTICS.MS_LATE=MONTHSTATISTICS.MS_LATE+1
     WHERE MONTHSTATISTICS.STA_ID=:NROW.STA_ID AND MONTHSTATISTICS.MS_YEAR=EXTRACT(year from :NROW.AR_DATE) AND
        MONTHSTATISTICS.MS_MONTH=EXTRACT(month from :NROW.AR_DATE);
	 UPDATE MONTHSTATISTICS SET MONTHSTATISTICS.MS_SALARY=MONTHSTATISTICS.MS_SALARY-20
     WHERE MONTHSTATISTICS.STA_ID=:NROW.STA_ID AND MONTHSTATISTICS.MS_YEAR=EXTRACT(year from :NROW.AR_DATE) AND
        MONTHSTATISTICS.MS_MONTH=EXTRACT(month from :NROW.AR_DATE);
  END IF;
  IF :NROW.IS_LEV_EARLY='1'
  THEN
     UPDATE MONTHSTATISTICS SET MONTHSTATISTICS.MS_LEA_EARLY=MONTHSTATISTICS.MS_LEA_EARLY+1
     WHERE MONTHSTATISTICS.STA_ID=:NROW.STA_ID AND MONTHSTATISTICS.MS_YEAR=EXTRACT(year from :NROW.AR_DATE) AND
        MONTHSTATISTICS.MS_MONTH=EXTRACT(month from :NROW.AR_DATE);
	 UPDATE MONTHSTATISTICS SET MONTHSTATISTICS.MS_SALARY=MONTHSTATISTICS.MS_SALARY-20
     WHERE MONTHSTATISTICS.STA_ID=:NROW.STA_ID AND MONTHSTATISTICS.MS_YEAR=EXTRACT(year from :NROW.AR_DATE) AND
        MONTHSTATISTICS.MS_MONTH=EXTRACT(month from :NROW.AR_DATE);
  END IF;
  IF :NROW.IS_ABSENT='1'
  THEN
     UPDATE MONTHSTATISTICS SET MONTHSTATISTICS.MS_ABSENT=MONTHSTATISTICS.MS_ABSENT+1
     WHERE MONTHSTATISTICS.STA_ID=:NROW.STA_ID AND MONTHSTATISTICS.MS_YEAR=EXTRACT(year from :NROW.AR_DATE) AND
        MONTHSTATISTICS.MS_MONTH=EXTRACT(month from :NROW.AR_DATE);
     UPDATE MONTHSTATISTICS SET MONTHSTATISTICS.MS_SALARY=MONTHSTATISTICS.MS_SALARY-100
     WHERE MONTHSTATISTICS.STA_ID=:NROW.STA_ID AND MONTHSTATISTICS.MS_YEAR=EXTRACT(year from :NROW.AR_DATE) AND
        MONTHSTATISTICS.MS_MONTH=EXTRACT(month from :NROW.AR_DATE);
  END IF;
END;
/
ALTER TRIGGER "C#SCOTT"."ATTENDANCERECORD_TRIGGER1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LEAVERECORD_TRIGGER1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C#SCOTT"."LEAVERECORD_TRIGGER1" 
  AFTER
  INSERT
  ON "LEAVERECORD"
  REFERENCING NEW AS NROW
  FOR EACH ROW
DECLARE
 

BEGIN -- executable part starts here
  UPDATE MONTHSTATISTICS SET MONTHSTATISTICS.MS_LEAVE=MONTHSTATISTICS.MS_LEAVE+:NROW.LR_DAYS
  WHERE MONTHSTATISTICS.STA_ID=:NROW.STA_ID AND MONTHSTATISTICS.MS_YEAR=EXTRACT(year from :NROW.LR_START_TIME) AND
        MONTHSTATISTICS.MS_MONTH=EXTRACT(month from :NROW.LR_START_TIME);
  UPDATE MONTHSTATISTICS SET MONTHSTATISTICS.MS_SALARY=MONTHSTATISTICS.MS_SALARY-:NROW.LR_DAYS*80
  WHERE MONTHSTATISTICS.STA_ID=:NROW.STA_ID AND MONTHSTATISTICS.MS_YEAR=EXTRACT(year from :NROW.LR_START_TIME) AND
        MONTHSTATISTICS.MS_MONTH=EXTRACT(month from :NROW.LR_START_TIME);
END;
/
ALTER TRIGGER "C#SCOTT"."LEAVERECORD_TRIGGER1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STAFF_TRIGGER1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C#SCOTT"."STAFF_TRIGGER1" 
  AFTER
  INSERT
  ON "STAFF"
  REFERENCING NEW AS NROW
  FOR EACH ROW
DECLARE
  ps INTEGER;
BEGIN 
   SELECT PO_SALARY INTO ps
   FROM POSITION
   WHERE PO_TITLE=:NROW.PO_TITLE;
   INSERT INTO MONTHSTATISTICS
   VALUES(:NROW.STA_ID,'2016','7','0','0','0','0','0',ps);
   INSERT INTO MONTHSTATISTICS
   VALUES(:NROW.STA_ID,'2016','8','0','0','0','0','0',ps);
   INSERT INTO MONTHSTATISTICS
   VALUES(:NROW.STA_ID,'2016','9','0','0','0','0','0',ps);
   INSERT INTO MONTHSTATISTICS
   VALUES(:NROW.STA_ID,'2016','10','0','0','0','0','0',ps);
   INSERT INTO MONTHSTATISTICS
   VALUES(:NROW.STA_ID,'2016','11','0','0','0','0','0',ps);
   INSERT INTO MONTHSTATISTICS
   VALUES(:NROW.STA_ID,'2016','12','0','0','0','0','0',ps);
   INSERT INTO MONTHSTATISTICS
   VALUES(:NROW.STA_ID,'2017','1','0','0','0','0','0',ps);
   INSERT INTO MONTHSTATISTICS
   VALUES(:NROW.STA_ID,'2017','2','0','0','0','0','0',ps);
   INSERT INTO MONTHSTATISTICS
   VALUES(:NROW.STA_ID,'2017','3','0','0','0','0','0',ps);
   INSERT INTO MONTHSTATISTICS
   VALUES(:NROW.STA_ID,'2017','4','0','0','0','0','0',ps);
   INSERT INTO MONTHSTATISTICS
   VALUES(:NROW.STA_ID,'2017','5','0','0','0','0','0',ps);
   INSERT INTO MONTHSTATISTICS
   VALUES(:NROW.STA_ID,'2017','6','0','0','0','0','0',ps);

END;
/
ALTER TRIGGER "C#SCOTT"."STAFF_TRIGGER1" ENABLE;
